export const qk = {
  akun: (platform?: string) => ['akun', platform ?? 'all'] as const,
  akunOne: (id: string) => ['akun', 'one', id] as const,
  katalog: (params: Record<string, string | number | boolean | undefined>) => ['katalog', params] as const,
  katalogRingkasan: (params: Record<string, string | undefined> = {}) => ['katalog', 'ringkasan', params] as const,
  katalogOne: (id: string) => ['katalog', 'one', id] as const,
  produk: () => ['produk'] as const,
  produkOne: (id: string) => ['produk', 'one', id] as const,
  listing: (produkId?: string) => ['listing', produkId ?? 'all'] as const,
  gudang: () => ['gudang'] as const,
  stokLedger: (produkId?: string) => ['stok-ledger', produkId ?? 'all'] as const,
  pesanan: (params: Record<string, string | undefined>) => ['pesanan', params] as const,
  pesananDaftar: (params: Record<string, string | number | undefined>) => ['pesanan', 'daftar', params] as const,
  pesananRingkasan: (params: Record<string, string | undefined>) => ['pesanan', 'ringkasan', params] as const,
  dashboard: (dari: string, sampai: string) => ['dashboard', dari, sampai] as const,
  pesananOne: (id: string) => ['pesanan', 'one', id] as const,
  users: () => ['users'] as const,
  staffAkun: (userId?: string) => ['staff-akun', userId ?? 'all'] as const,
  settlement: (params: Record<string, string | undefined>) => ['settlement', params] as const,
  settlementPesanan: (params: Record<string, string | number | undefined>) => ['settlement-pesanan', 'daftar', params] as const,
  settlementRingkasan: (params: Record<string, string | undefined>) => ['settlement-pesanan', 'ringkasan', params] as const,
  settlementOne: (id: string) => ['settlement', 'one', id] as const,
  laporanRingkas: (dari: string, sampai: string) => ['laporan-ringkas', dari, sampai] as const,
  iklanHarianToko: (params: Record<string, string | number | undefined>) => ['iklan-toko', 'harian', params] as const,
  iklanRingkasan: (params: Record<string, string | undefined>) => ['iklan-toko', 'ringkasan', params] as const,
  kampanyeIklan: (akunId: string, hari: number) => ['iklan-kampanye', akunId, hari] as const,
  campaign: (params: Record<string, string | undefined>) => ['iklan', params] as const,
  campaignOne: (id: string) => ['iklan', 'one', id] as const,
  metrikHarian: (campaignId: string) => ['iklan-metrik', campaignId] as const,
  laporanIklan: (campaignId: string, dari: string, sampai: string) =>
    ['iklan-laporan', campaignId, dari, sampai] as const,
}
